### ISSUE TITLE
Containers "remember" last active child 

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#106]
With Tree Paths finally merged in, containers now have the necessary information to determine which container was last active. This means switching focus will feel much more natural, as switching between different views that are children of container (or between different workspaces) will go the last active one.

**Comment by SnirkImmington** [comment]
"Go to last workspace" is a pretty standard Awesome feature (that I don't use) - is that possible to implement with the current way paths are implemented?

**Comment by Timidger** [comment]
Hmm, right now currently _no_ unfortunately. What the paths do is simply allow us to follow the current "active path". Once a path is no longer active, it is deactivated with no additional metadata about when it was last active. Active edges _beneath_ that may still be active, but it won't be part of the main path. To be able to implement that feature something else will need to be done with paths. I'd like to keep the "active" as a simple binary flag but something else could be worked out so that we have a better history of actions.
