### ISSUE TITLE
Split background into a separate program

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#109]
The code that currently deals with drawing the background (`background.rs`) should be relegated to a different program/repo. Since it is dealt with as its own surface, it's best dealt as a separate client program. 

There are difficulties with how to integrate this in terms of packaging with Way Cooler, but this is a discussion that would have come up sooner or later as our client programs improved.

@SnirkImmington, is there anything we can/should do now, or should we put this off until we start doing binary distributions. One immediate solution we can do, at least for Arch, is to have another package for this and mark it as "optional" for Way Cooler.

**Comment by SnirkImmington** [comment]
I don't think there are _any_ users who want _absolutely_ **no** control of the background. There's no reason to force _everyone_ to download a client just to use Way Cooler (and if you're installing lots of things/using an automated program/using a GUI the "optional" list can blur past or not be seen). The fact that it "deals with its own surface" is just an implementation detail. 

On the flip side, we should figure out how to package clients/extensions/plugins. Something that this reminded me of is Rust's standard libraries - `std` (i.e. Way Cooler) can provide the foundations, but lots of people are going to want other dependencies (client programs) to use the system well. Especially for cases like this, where the tipping point is kind of over how much we want to follow unix philosophy, we could do what has been suggested for Rust - promote certain clients to "core" status, and include them in the standard distribution/init file. This would also match with our original ideas of providing "distributions".

However, client libraries here are going to have a bit more "weight" than metaphorical Rust dependencies. If Way Cooler can be described as "that tiling Wayland window manager where you need a whole program just for a background," I can see a lot of skepticism being directed at us - regardless of our intentions, it would look bad.

**Comment by Timidger** [comment]
I think you are misunderstanding me. Right now, in our alpha state, yes it would be an annoyance because we don't provide any packaging. Later on, we would bundle it all together and it would not even be noticed that it's a side thing. By pushing it to an exterior program, it allows us to remain flexible. If a protocol comes along that everyone rallies around (e.g desktop-shell, which sway uses), then it'll be easier for someone to make something like `nitrogen` for wayland.

Sway and i3 are good examples of this actually: i3 and sway both have separate programs for the bar, and sway has a separate program for the background as well. No one has ever complained about having to have "a whole program just for a background" for sway, because it's not a problem.

Things like this may not be very optional, that's a good point. But we should try and keep things modular regardless. We can package this program up with Way Cooler as well in the Arch repos, and even keep it in the same git repo and just have it as a separate crate.
