### ISSUE TITLE
Improve init file search logs and remove user information

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#112]
At the moment we rely on error logs for debugging and to provide feedback to users. @vinipsmaker has suggested removing any personal or specific information from these logs so users don't feel they have to comb through them and we don't leak any unnecessary information. He specifically pointed out the home directory/user name in the init file logs. They look something like this right now:
```text
WARN [lua::init_path] src/lua/init_path.rs:42 $XDG_CONFIG_HOME=/home/snirk/.config, was not a valid path to a config file. Defaulting ... 
TRACE [lua::init_path] src/lua/init_path.rs:47 Looking at "/home/snirk/.config/way-cooler/init.lua"
INFO [lua::init_path] src/lua/init_path.rs:49 Reading init file from "/home/snirk/.config/way-cooler/init.lua"
```
The logs when searching for the init file should also be improved, as this is a very common mistake that we need to be more explicit about. Logs should instead look more like:
```text
INFO [lua::init_path] init_path.rs:40 Will search for config file at (1) $WAY_COOLER_INIT, (2) $XDG_CONFIG_HOME/way-cooler/init.lua, (3) ~/.config/way-cooler/init.lua, and default to /etc/way-cooler/init.lua
INFO [lua::init_path] init_path.rs:40 $WAY_COOLER_INIT not defined, looking in regular directories... (1)
INFO [lua::init_path] init_path.rs:42 Found environment variable $XDG_CONFIG_HOME=~/.config, but did not find ~/.config/way-cooler/init.lua (2)
WARN [lua::init_path] init_path.rs:47 The user config file ~/.config/way-cooler/init.lua was not found. Will default to /etc/way-cooler/init.lua (3)
ERROR [lua::init_path] init_path.rs:48 Could not find /etc/way-cooler/init.lua - you need the way-cooler init file to use way-cooler!

way-cooler could not find an init.lua to use. We have looked for it {list of places}. You need an init.lua file to use way-cooler.
We supply a default init.lua in our GitHub releases:
<link to this version's GitHub init file>
You should install that to /etc/way-cooler/init.lua as a backup, and copy it to your config folder {~/.config or $XDG_CONFIG_DIR if it was defined before}/way-cooler/init.lua and do your modifications there. 
Alternatively, you can use the $WAY_COOLER_INIT variable when running way-cooler to point directly at the file way-cooler should use.
```
Those last couple of lines would be printed directly to stdout.

We should also consider compiling the default init file into way-cooler (to be used after `/etc/way-cooler/init.lua` - but this raises more questions and prompts more discussion (is this a good idea for when we release different "styles"? Does this affect the discoverability of the init file? When we have more standard methods of distribution will this be a problem?)

Also, having Lua restart with a different init file during the initialization phase (i.e. "default to /etc/way-cooler/init.lua") is a separate issue.

**Comment by Timidger** [comment]
I have no problem with compiling a default into Way Cooler, it will improve the stability of the window manager, providing we print out to the log that we are defaulting because we couldn't find one. It can be very bare bones, whereas we can have one in a separate file that is more "full featured" with the "styles" and other features.

**Comment by Timidger** [comment]
This seems mostly a dup of #118, is it safe to close?

**Comment by SnirkImmington** [comment]
Most of this is complete (the text isn't super fancy yet), and we're planning on including the init file with way-cooler in the next version, so I will close this issue.
