### ISSUE TITLE
Segfault on startup due to background

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#117]
The background image is loaded up, and then mysteriously destroyed just a moment later. This causes a segfault, and Way Cooler terminates. Tested as of 034dcbe (current master), on Arch Linux 64bit.

WORKAROUND: Set the color in the configuration file to be empty, and it should work as the background will then not load.

**Comment by SnirkImmington** [comment]
Duplicate of #115 || fixed in 21bd2c4 ?

**Comment by Timidger** [comment]
Not dup, but was mentioned. This is a separate issue.
