### ISSUE TITLE
Print warning message for proprietary Nvidia driver users

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#119]
Users of proprietary Nvidia drivers will not be able to use Way Cooler. Nvidia has not released support for Wayland in their drivers, and so nouveau will need to be used. Sway [does something similar already](https://github.com/SirCmpwn/sway/blob/04db58863e38c800c73736df1910b5164cb66db7/sway/main.c#L55), and it would benefit debugging user issues if we include this kind of check as well.

**Comment by SnirkImmington** [comment]
I always get my hopes up that way-cooler will run on my desktop tty (it won't), we should definitely do this.
