### ISSUE TITLE
Improve messages when loading init files

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#125]
Currently `way-cooler` will log some kind-of-helpful messages about where it looking for the `init.lua` file. It should instead print to stdout exactly where it looked, and what the user could do to help `way-cooler` locate an init file. 

Waiting for #124 to allow `way-cooler` to revert to a default init file. Split from #118.

**Comment by Timidger** [comment]
Hasn't this been fixed already? We are pretty verbose with logging when looking for the config file.
