### ISSUE TITLE
Reloadable init file

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#126]
Currently, `way-cooler` will crash if it has problems loading its init file. However, the user should be able to use a keybinding to reload the init file in-place (without restarting the window manager or disconnecting any clients). This will require separating the options specified in the init file (i.e. keybindings) from the rest of way-cooler itself. 

Waiting for #124 and #125. Split from #118.

**Comment by Timidger** [comment]
Already fixed / dup
