### ISSUE TITLE
dmenu not appearing correctly

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#150]
dmenu appears sometimes, but then immediately disappears and is unavailable. An xcb x11 error is printed to the log when this occurs.

**Comment by SnirkImmington** [comment]
Is that the error reported in https://github.com/Cloudef/wlc/issues/208? I remember seeing that but I'm not sure if it was happening when opening or closing programs.

**Comment by Timidger** [comment]
No, this has been fixed. It was an issue in Way Cooler
