### ISSUE TITLE
Popup windows are not handled correctly

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#151]
Popup windows (eg from context menus, like in the browser or when right clicking in most applications) does not work properly. The window appears, and then immediately disappears. Might, or might not, have to do with #150.

**Comment by SnirkImmington** [comment]
Finding a window which is a context menu or other floating window should be possible by checking the `class` of the window, assuming the application developer has labeled them as such. I believe the wlc example ignored tiling such windows, now that we have good floating support do you think we should auto-float popup windows?

**Comment by Timidger** [comment]
Like #150, has been fixed (same bug)

**Comment by Timidger** [comment]
popup windows are already auto-float
