### ISSUE TITLE
Add way-cooler to gdm

### ISSUE THREAD

**Issue by brunoqc** [Immington-Industries/way-cooler#154]
I installed the AUR package and way-cooler is not in gdm's window manager list.

**Comment by starfys** [comment]
Which AUR package? ```way-cooler``` or ```way-cooler-git```?

**Comment by brunoqc** [comment]
way-cooler

**Comment by starfys** [comment]
I don't run GDM so this may not work, but try writing the following to `/usr/share/xsessions/way-cooler.desktop
`

```
[Desktop Entry]
Encoding=UTF-8
Name=way-cooler
Comment=Customizable Wayland compositor
TryExec=way-cooler
Exec=way-cooler
Type=Application
```

**Comment by brunoqc** [comment]
It works.

Maybe you could do a PR to have this file included. Maybe with the name "Way Cooler" so it looks good with other items like "GNOME on Xorg" and "Weston".

**Comment by Timidger** [comment]
Ha, I had been just thinking about doing this my self (it's too annoying logging in each time to a tty). Thanks @starfys for the `.desktop` file.

Feel free to open a PR to have this file included. Once it's in I can message @vinipsmaker to update the AUR recipe.

**Comment by starfys** [comment]
Can do! Where in the repository should I put `way-cooler.desktop` ?

**Comment by Timidger** [comment]
Root folder should be fine, as we add more of these meta files we may move it to a better dumping ground for these things. But for now root folder should be fine

**Comment by krazedkrish** [comment]
how can i run via tty?
can i run using xinit and modifying ~/.xinitrc
thanks in advance for answering my question!

**Comment by Timidger** [comment]
To run on tty, just run the binary itself (eg `way-cooler`)
