### ISSUE TITLE
Lua features

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#16]
These features are needed for the Lua thread:

### IPC
- [x] Lua thread is an internal IPC client
- [x] Lua can register its own callbacks to IPC events (i.e. keybindings)
- [ ] Accept terminate and restart commands
- [ ] Use move semantics/clone-on-write for `Arc` values from the registry to prevent some copying

### Libraries
- [x] Lua called through init script
- [x] Invisible wrapper to registry
- [ ] Registry fields with nested names
- [ ] JSON support

Most of the value of the Lua thread comes from compatibility with the configuration, commands, keybindings, etc.

**Comment by SnirkImmington** [comment]
Updated to reflect Lua thread being downgraded to an internal IPC client.

**Comment by Timidger** [comment]
What is the status on these features? If they are still open, we should begin to move them into separate issues so that they can be better tracked.

**Comment by SnirkImmington** [comment]
Okay, I'll close this issue and open a couple smaller ones.
