### ISSUE TITLE
Exiting dmenu does not return focus

### ISSUE THREAD

**Issue by valryne** [Immington-Industries/way-cooler#164]
When exiting dmenu prematurely or executing something invalid (like 'mupdf'), such that dmenu exits without anything happening, it does not return focus to the last active container. 

In fact, there is no active container thereafter and #63 applies.

I am using the generic dmenu package of Arch that targets X11.
This could also be a problem with dmenu itself or XWayland, which I believe is used to run dmenu.

**Comment by Timidger** [comment]
This is a specific version of #130, it has been fixed in the 0.4.1-fixes branch. There will be a pull request with this fix in it later today. It will be in master shortly.
