### ISSUE TITLE
Commands & keybindings features

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#17]
These features are needed to use commands and keybindings (see [way-cooler/tree/registry-rejson](https://github.com/Immington-Industries/way-cooler/tree/registry-rejson)):

- [X] Keybindings use commands from the registry
- [ ] Key presses can be sent through IPC
- [x] Lua can register key handlers in init script
- [ ] Reconfigure keybindings at runtime

**Comment by SnirkImmington** [comment]
Updated to reflect changes in Lua thread design.

**Comment by Timidger** [comment]
I'm going to go ahead and close this, so that we can chunk this up into individual issues to deal with and delegate them better.
