### ISSUE TITLE
Tiling features

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#19]
These features are desired of the way-cooler tiling algorithm (see [way-cooler/tree/tiling](https://github.com/Immington-Industries/way-cooler/tree/tiling)):

### Workspaces
- [x] Can have names or use numbers
- [ ] Can be generated on the fly or exist as a static list
- [x] Each monitor can have its own workspace list, 
- [ ] or the list is global across all outputs 
- [x] Can move containers between workspaces

### Containers
- [x] Views are assigned to containers
- [x] Containers can tile horizontally or vertically
- [x] Containers can be nested
- [x] Containers can be controlled i3 style
- [ ] Can move containers to other containers
- [ ] Custom tiling patterns so container keybindings aren't needed

### Views
- [x] Try not to tile views that don't want to be tiled
- [ ] Floating views

**Comment by Timidger** [comment]
A lot of this stuff is still up in the air, but I'm going to go ahead and close it since we have the majority of the features and they should exist as separate issues now.
