### ISSUE TITLE
x11 crashes when switching from way-cooler vt back to x11 vt

### ISSUE THREAD

**Issue by raboof** [Immington-Industries/way-cooler#190]
When running way-cooler on vt1 and x11 on vt7, when switching from vt1 directly to vt7 my X11 tends to crash. From the Xorg.log:
```
modeset(0): drmSetMaster failed: Invalid argument
modeset(0): failed to set mode: Permission denied
```

However, when I switch from vt1 to vt7 via vt2, it works reliably. The theory is that way-cooler is giving up being the DRM master when switching vt's, but not quickly enough.

**Comment by raboof** [comment]
I can confirm I can also reproduce this with orbment. Looking with gdb it appears wlc never calls `drmDropMaster` even when it does work.

**Comment by Timidger** [comment]
Needs to be fixed wlc side.
