### ISSUE TITLE
IPC features

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#20]
These are the planned features for inter-process communication with way-cooler:

### Command Socket
- [x] Available at ~~`/tmp/way-cooler/socket`~~ `/run/way-cooler/<ID>/socket`
- [x] An environment variable is set to indicate what `<ID>` is.
- [X] Socket handles the case when there was previous or multiple way-cooler instances.
- [x] Socket handles requests in a multithreaded way
- [x] Socket accepts and replies with JSON packets
- [ ] Socket accepts requests for event listeners

### Packets
- [x] `get` get values from registry
- [x] `set` set values in the registry
- [x] `exists` see if a value exists
- [X] `run` to run a command
- [X] `version` to query version
- [X] `commands` to list commands

### Lua IPC
- [x] Lua thread registered as internal IPC client
- [ ] Lua can register event handlers

In addition, we need an event API.

**Comment by SnirkImmington** [comment]
Updated with new goals for Lua thread.

**Comment by SnirkImmington** [comment]
Updated with goals for command/event socket.

**Comment by Timidger** [comment]
I'm going to go ahead and close this issue, since we've accomplished most of it and any event stuff should go into its own separate issue.

**Comment by SnirkImmington** [comment]
IPC success!
