### ISSUE TITLE
Does this work with EGL Streams?

### ISSUE THREAD

**Issue by StefanoD** [Immington-Industries/way-cooler#212]
Then it would work with NVIDIA drivers, too.

**Comment by Timidger** [comment]
Nope, see [this wlc thread](https://github.com/Cloudef/wlc/issues/138). I feel your pain, I have to use integrated graphics on my desktop with Way Cooler. I would look into this myself, but I have enough on my plate w/ Way Cooler. Perhaps in the future someone else can provide a patch, until then though Way Cooler will not work correctly with proprietary Nvidia drivers.

**Comment by jscinoz** [comment]
Just a reference if anyone else reading this later wants to give this a shot (I might do so myself when time allows, but no idea when that'll be): Gnome's (or rather, Mutter's) [EGLStreams patches](https://github.com/jadahl/mutter/tree/wip/egldevice)

**Comment by jscinoz** [comment]
FWIW, EGL stream support appears to have been merged into wlc: https://github.com/Cloudef/wlc/pull/245

**Comment by ratmice** [comment]
@Timidger This seems to work somewhat now (although having some driver instability)
To get it working on fc27 i basically had to install the proprietary drivers, and remove this check:

https://github.com/way-cooler/way-cooler/blob/master/src/main.rs#L121-L125

Not sure if there is a way to check whether the wlc supports egl streams or not, or if it would enough to just bump the version of wlc required.

**Comment by Timidger** [comment]
WLC since... 0.0.7 or so has support egl streams, so the answer given to this issue is out of date. Note that wlroots does _not _ support it, and when we transition to it the support will go away

**Comment by Timidger** [comment]
@ratmice that line you linked just issued a warning, it shouldn't stop the start up sequence

**Comment by ratmice** [comment]
@Timidger Ahh, as I said having driver instability, Its likely that when i tried it and got the warning the device was already in some bad state..
