### ISSUE TITLE
Log output should go to a file

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#51]
We should write the log output to a file, which makes it easier to see what went wrong and let us pretty print some more.

We should also make it possible to clear log output automatically if Way Cooler quit successfully, and otherwise keep it around. We can do this by stamping out `/var/log/way-cooler-<timestamp>`, which will make each one unique.

This can remain configurable, in order to not chew up people's disks, or if we want to keep log output even if we successfully quit.

**Comment by Timidger** [comment]
Hmm this is for some reason very hard. `env_logger` and `log` don't seem to provide options to write to a different `File`, and we can't keep a file open for the entirety of the program because we can't be sure it closed and flushed all of its output because it's `Drop` is never called. 

Would this be better to implement in the install/build script by wrapping `way-cooler` in a bash script that uses `tee` to pipe to `stderr` as well as `/var/log/way-cooler`?

Am I missing something @SnirkImmington?

**Comment by SnirkImmington** [comment]
`log` itself only provides declaring logs. There are other crates that do things with those logs.

**Comment by Timidger** [comment]
Moving discussion over to #87, as that is the solution we have decided to go with.
