### ISSUE TITLE
Some commands (like window close) command doesn't work

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#57]
I noticed some commands don't seem to be working now (such as close window, normally alt+q) does this have to do with changes made in xkb @SnirkImmington? This also changes depending on whether running with `cargo run` or `cargo build`. While debugging #52 I came across this issue, so it may have to do with that as well.

**Comment by Timidger** [comment]
Interesting, when I test with US keyboard there is no problem, but on my dvorak layout some keybindngs, such as `close_active` does not work. Any ideas why? I assume it has to do with the keysym not converting properly from the actual key to the key number. I have tried using the key where Q is supposed to be, but that is the `'` key and unfortunately doesn't change anything.

**Comment by Timidger** [comment]
Possible data race somewhere between the key initialization, commands being filled in the map, the registry starting up, and reading the keybindings from the configuration file?

**Comment by SnirkImmington** [comment]
I was looking into the data raciness but from what I can tell the commands are initialized and everything is added in the init file, just the keys in the callbacks were giving back nothing. I'll look into combing over locks on the various structures and moving Lua initialization to outside of compositor init.

**Comment by SnirkImmington** [comment]
Update: not a data race (:tada:), looks like issues with keysyms. We "split" the modifiers (shift, alt, etc.) off of the keysym via the wlc method `wlc_get_keysym_for_key` and it looks like sometimes the keysyms we get back have a "shift" applied to them - `L` and `D` instead of `l` and `d` for the dmenu stuff, and the symbols instead of the numbers. This could be our bindings being bad, not passing the right modifiers in to wlc, and it definitely only happens sometimes.

**Comment by Timidger** [comment]
Can we just lower them and call it a day? Do we ever depend on them being capitalised? Or does it actually apply shift to the list of modifiers?

**Comment by SnirkImmington** [comment]
By capitalized I mean calling `get_name` on the keysym we get back sometimes returns this "capitalized" sym. This happens after we strip the modifiers - including shift - to everything during _some_ entire way cooler sessions.
