### ISSUE TITLE
Support changing the screen brightness through fn keys

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#67]

**Comment by Timidger** [comment]
Hm, technically isn't this available already to us by binding the screen brightness keys to a lua function. The only thing that may need to be supported is better ways to specify keys (right now we use names from xkbcommon only)

Changing screen brightness already has a plethora of options for linux, see [this wiki page](https://wiki.archlinux.org/index.php/backlight#Backlight_utilities) for different utilities that can be used.

**Comment by valryne** [comment]
I just installed release 0.4 and the fn+FX keys for backlight adjustment work out of the box.
way-cooler started in tty on current Arch install; 
backlight controlled through acpi and fn+FX already works in tty
hope this helps

**Comment by Timidger** [comment]
OK, cool
