### ISSUE TITLE
Add support for background images

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#70]
Right now Way Cooler only supports solid color background images. There is strange behavior when attempting to write out the image buffer after reading it from an [image surface](http://gtk-rs.org/docs/cairo/struct.ImageSurface.html). 

Weird black lines appear on the image, and the color saturation seems to be depleted though the image is discernible.

Here's an example of what the output looks like:

![screen shot 2016-08-16 at 9 02 10 am](https://cloud.githubusercontent.com/assets/3515754/17699703/420fa032-6390-11e6-8fb0-2afb23573899.png)

and here's what it's supposed to look like:

![her](https://cloud.githubusercontent.com/assets/3515754/17699819/ecd43a78-6390-11e6-9863-4196fc68e683.png)

**Comment by leshow** [comment]
why does way-cooler have to draw backgrounds at all? does wayland not have tools like feh in order to set the background? Apologies if that sounds silly, it just seems to me like the background has nothing to do with tiling windows

**Comment by Timidger** [comment]
Unlike X, there is no Xorg program to rule them all. Instead, each compositor has to reimplement the functionality. This is a curse of consolidating both the compositor and the window manager into one. As Wayland is adopted, this will probably change because there will be standard libraries/protocols that every one can be based upon. For example wlc, the library we use to build Way Cooler, could implement this and then every wm using it would benefit (including Way Cooler). 

For now, the background is actually just like any other view, it's just treated specialy in the filing

**Comment by leshow** [comment]
Thank you for the explanation.

**Comment by SnirkImmington** [comment]
I had previously thought this was a gamma issue, but given those vertical bars it's probably not that.

I'll try to look into it later, just in case.

**Comment by Timidger** [comment]
Issue resolved with [this repo](https://github.com/Immington-Industries/way-cooler-bg)
