### ISSUE TITLE
Closing a window (with close_window command) that has a pop-up "Are you sure" dialog has strange behavior

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#83]
I'll use emacs as an example. If you edit a open file buffer in emacs, but don't save your changes, if you try to close the window (i.e with `alt+q`) then a dialog box opens asking you questions on how it should deal with the file.

Here, different things can happen:

* If you choose to e.g look at the buffer, then we've already removed it from the tree. This means that you can freely do things in emacs (for the most part) but it will no longer behave with the rest of the containers in the tree. If it was the only app open, then all other apps are now obscured. The only fix is to open a terminal and type in `pkill emacs`, and wait for the buffer to be garbage collected.
* If you choose to close the window (saving or not) then the window is properly closed but the display/ buffer s not cleared, so the last view you had of emacs will stay up (but non-interactable, since its not really "there") and obscuring things until you switch to a window where those pixels can be overwritten.

**Comment by Timidger** [comment]
This might be solved by changing `remove_active` to only call `view.close` and let the `view_destroyed` callback deal with tree removal.

**Comment by SnirkImmington** [comment]
Fixed in #99
