### ISSUE TITLE
Move logging over to slog

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#87]
We need much more structured logging, [slog](https://github.com/dpc/slog-rs) looks like it has the features we want (filtering based on some meta-data, multiple-outputs so we can log to a file and keep it around if it crashes.

**Comment by Timidger** [comment]
We should have a special debugging call that should never be on the repo. Add a hook to github/git using grep so that this never happens.

**Comment by SnirkImmington** [comment]
To sum up what we need:
- Easy to find/persist/submit logs for users that provide enough debugging info without being nosy and aren't obtrusive
- Toggling off of certain debugging and trace messages (i.e. when the layout code freaks out and debug-prints the whole tree, or if an action flowing between Lua and the library needs to be traced) such as by class, module, level
- Better colors/etc for differentiating levels
- A debugging level used while working on a feature, that could be super verbose, to be stripped before being merged in

**Comment by Timidger** [comment]
To clarify the last point:  a debug mode that is checked on PRs and the PR is denied if it is found was what we agreed upon?

**Comment by SnirkImmington** [comment]
Ideally - this could be implemented as a clippy lint (maybe) or even just a grep through PR diffs whether online or in a push hook.

**Comment by Timidger** [comment]
Yeah, that's what I was thinking. If that's too complicated we can just have a more informal setup where it's on the onus of the reviewer to make sure that the pusher isn't forgetting anything

**Comment by SnirkImmington** [comment]
I think it's a good idea to leave things like that - automated testing is never going to completely verify a PR and we need to ensure we're looking hard enough - if some gets into master that's the reviewer's fault 😛

**Comment by Timidger** [comment]
probably not going to happen for a while
