### ISSUE TITLE
Consider statically linking to wlc

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#89]
There have been issues when the wrong version wlc is used, and there are confused users such as #84. This could also help later with packaging Way Cooler, because we could distribute as a single binary. 

This might bloat up the size of it a bit more, but it should be able to work. Do you have any strong thoughts on this @SnirkImmington?

**Comment by SnirkImmington** [comment]
Last we talked about it, we were considering including wlc in a build script. However, we don't want to be compiled from source forever. Although `cargo` is the de-facto Rust distribution method now, we'd like to move away from being tightly bound to the language. Rust is already nice enough to statically link itself, so when we start distributing binaries no one will know the difference (we can take "written in Rust" out of our descriptions). 

This more plays into whether we want to distribute as a binary or compile-from-source, especially in alpha. If you want to move to that sooner, sure, we can set up a script with rustc to compile and statically link on various platforms and distribute zipped binaries in GitHub releases.

**Comment by Timidger** [comment]
We don't need to worry about binary distribution for a while, but I'm going to assume it'll take effort to get into most package managers. Notice sway isn't in e.g Ubuntu/Debian or Fedora yet. This is because wlc is the blocker with that. We could just distribute our own `way-cooler.tar.gz`, but then we need to have additional instructions on where to put `libwlc.so` or some other "install script" which I definitely don't want to maintain.

In contrast, by switching to a static model even if we can't get Way Cooler into standard repos, distribution will be much simpler because the zip will just have to container Way Cooler and nothing else.

**Comment by SnirkImmington** [comment]
Okay, get a binary to distribute is probably the easiest solution. It would also fix some concerns with staying up to date with wlc. A concern is that it wouldn't play as nicely with package managers - some users would have two wlcs installed, probably the same version. I suppose we can provide an option in that case.

**Comment by Timidger** [comment]
Since wlc isn't very standard, I wouldn't worry about library duplication / bloat. Wlc is very small, I believe last I measured the static file was less than a megabyte. But yeah you can always build it dynamic from source

**Comment by SnirkImmington** [comment]
I was thinking we have a switch in the build script so the AUR for example can specify wlc from there but we can specify static linking for our distributions.

Pinging @Cloudef, do you have any concerns with wlc library users statically linking to your lib and distributing with it? We have an MIT license and would definitely mention including it.

**Comment by Cloudef** [comment]
wlc is also MIT licensed (to be compatible with wayland license). I don't have anything against static linking and it might be wise during unstable builds especially. I especially recommend at least that chck is statically linked into wlc at least, since it's low level library that exposes all structures.

**Comment by Timidger** [comment]
Good to hear, thanks. We'll be sure to build chck in as well.

**Comment by SnirkImmington** [comment]
Handled by https://github.com/Immington-Industries/rust-wlc/issues/55 and #98.
