### ISSUE TITLE
Move over to dbus for IPC

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#91]
Our ad-hoc IPC socket does not look like it will scale well for our needs. Lets look into moving over to dbus, [this](https://github.com/diwic/dbus-rs) crate looks mature enough to use.

**Comment by SnirkImmington** [comment]
Moving discussion of #76 here - we have API design to consider:
* We can transfer the concepts of the registry get/set/RPC over to dbus
* The crate you linked is mature-ish, but plagued by terrible design. We can push some IPC functions straight over to that crate's registration, but not all of them.
* We'll still want a place to hold some general configuration - i.e. background color/image, default terminal/editor, etc.
* We'll also still want the upcoming event-bus.
* As stated in #76, individual parts of way-cooler want specific configuration that's a lightweight struct. Consider layout options, layout scripts, background settings, window/tag rules, etc. Avoiding the overhead of `HashMap`s, `Arc`s, and Json parsing would be cool. We should still have these as objects on the d-bus - but maybe we want to update them straight through the event bus or IPC

Moving away from a central registry might be a good idea - d-bus's concept of object paths makes our API less uniform. We also have less reason to use Json - d-bus handles types for us. Maybe we can switch to a model of different modules owning their own configuration, receiving changes from IPC and sending back events. This would also make the event bus a thinner wrapper over d-bus itself.

1. We can stay closer to the old design - have a library of JSON objects and properties, keep that in sync with structs in the other modules, and route d-bus requests through it
2. We can scrap the idea of a central library all together (aside from our d-bus specification) and route d-bus requests directly to different modules.

**Comment by Timidger** [comment]
Hmm, the idea of scrapping the central library and having each d-bus request go directly to the required module is really interesting. It would simplify things a bit, and if we ever wanted to share configuration details between modules we can work around that within the program with e.g `RefCell` and `Rc` to link them together, or design it so that the configuration details are read from parent module they share as an ancestor.

For the 'general' configuration, we would need to figure out where to store that configuration details, how it'll be modifiable at runtime so that others can keep up to date (essentially the same problem I detailed in the last paragraph). 

I haven't looked at the crate yet, sorry to hear it's poorly designed. Hopefully we can work around some of those issues.

**Comment by SnirkImmington** [comment]
> For the 'general' configuration, we would need to figure out where to store that configuration details, how it'll be modifiable at runtime so that others can keep up to date (essentially the same problem I detailed in the last paragraph). 

I think it'll be important for way-cooler API to have stricter definitions behind "init", "config", and "general API".

**Initialization** Obviously, we want some IPC clients to have more power than others, and the first client will be the init file. We should consider some parts of the API as "init options" - things that would need init auth or are most required to start using way-cooler (i.e. background image, layout options/scripts, workspace names, etc), could be write-once, and are least likely to change at runtime. These basically are required to be set in the init file, and way-cooler would be difficult/impossible to use without them. Also includes things that couldn't change at runtime.

**Configuration** Most likely held in the structs you described in #76, just a way to power different parts of way-cooler (how to lay out workspaces, rules, tree options, themes, notification preferences). Should be "hot" structs held by different components, but also should be configurable over IPC. Should mostly be key/value stuff inside structs, shouldn't include RPC, should be  set over IPC/read by way-cooler.

**General API** The way-cooler application programming interface covers everything else - exposing events over d-bus, keybindings, rule matching, custom layout, etc. There would be overlap with init/config, but the API would mostly be RPC - i.e. the tree commands would be exposed here. The running of methods or the exposing of "live data" (i.e. get current workspace, the tree's layout as a JSON, get/set tags, etc.) would also go here. Way Cooler events and event handling would also go here.

It might help clients if we separate these out in d-bus (i.e. in different folders on the object path). If everything under `/init/` required init auth it would also make things easier.
