### ISSUE TITLE
Automate GitHub Deploys via Travis

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/way-cooler#98]
In order to release new versions of Way Cooler quickly and efficiently (including hotfixes), and to enable releasing binaries, we should use Travis to deploy releases to GitHub. The new release cycle would look like:
* Create branch/commits to update readme, Cargo.toml, Cargo.lock with new version
* Update wiki for version-specific changes/changelogs
* Merge version-specific changes in
* Push git tag for the version
* Travis handles some release stuff:
  * Updates docs
  * Compiles binaries for multiple architectures (linux, freeBSD, ARM versions)
  * Creates the GitHub release for that tag
  * Uploads binaries + `init.lua` to GitHub release
* Publish to `crates.io`
* Update AUR package/etc.
* Close any remaining issues, milestones, and Trello board posts

It would be _nice_ if Travis could also handle updating packages or other boilerplate that could accidentally be forgotten as well.

We _could_ go all out and use some scripts to update the readme/etc with version numbers but that's not needed. Statically linking binaries is another issue so we can wait for that.

For version **0.3.3**, I suggest we have:
- [x] Travis git-tag hook to post a GitHub release (OAUTH tokens, etc.)
- [x] Travis attaching `init.lua` and maybe the basic unlinked `way-cooler x86_64 linux` to the GitHub release

If we don't use Travis to automate anything else about our releases (like some kind of non-obsessive person), we should at least have a specific "playbook" for how we release: making a release branch, specific commits for updating the readme/docs/etc., and a specific order of running `cargo publish`, etc.

**Comment by Timidger** [comment]
This all sounds like a lot and can be easily automated with a release script. Travis can handle most of the heavy lifting, but it would be nice to have a script that can set that all in motion (including the Travis automation).

**Comment by SnirkImmington** [comment]
Travis will run things after tags are pushed. We would need the repo to reflect the new version before pushing the tag though.

**Comment by SnirkImmington** [comment]
Updated original comment - we should be making `release-x.y.z` branches and have Travis fail the builds if the release branches and tags don't update all the things. I've looked into cross-compilation with Rust (and C for `wlc`) and I'd like to include statically linked compiled binaries in the future.

**Comment by SnirkImmington** [comment]
Most of this is handled in `travis-deploy`, although we won't really know whether it works until we try it. Statically linking is of course something we need to handle in `rustwlc` and `wlc-sys`.
